### ISSUE TITLE
lite版本的实现

### ISSUE THREAD

**Issue by ShiinaRinne** [ShiinaRinne/genshin_task-resin-expedition_alert#24]
这是一个客户端只需要运行，定时传输数据到服务器的轻量版本。只需要配置接收消息的qq号、uid与cookie即可。

由一个qq机器人用来接收后端服务器的数据并在qq群内提示、群内私聊发送，或添加机器人好友私聊发送等

**Comment by yaomeng0722** [comment]
目前后端接口已经完成，还需要对qqbot的部分做修改，以支持对指定用户发送消息
临界条件的判断仍由机器人所使用的程序负责，需要支持主动查询
